[general]
import = [
    "~/.config/alacritty/tokyo_night_enhanced.toml"
]
[[keyboard.bindings]]
key = "H"
mods = "Control"
action = "None"
[window]
# startup_mode = "Fullscreen"
opacity = 0.92
blur = false
padding = { x = 20, y = 10 }
dynamic_padding = true

[font]
size = 20
